#root file

Seed: 1

data_path: 'F:\Landsat Download\Scenes2 CN\DL'

save_path: 'F:\deep leaning\UTRnet\UTRnet\models'

begin_time: 0
time: 10
# training Params
max_epoch: 50
start_epoch: 0
n_classes: 2
learning_rate: 0.001
learning_rate_abcd: 0.01
batch_size: 500
image_time: [6.7507, 5.9616, 5.0411, 4.1644, 3.9452, 3.1562, 2.7178, 1.8849, 0.2192, 0]

steps: [10,15,20,25,30,35,40,45]
lr_gamma: 0.5

mode: LSTM   #  LSTM / TimeLSTM  / Distanced_LSTM  / UTRNet

# loss Params
loss_name: cross_entropy_loss
# valid_size: 0.1
adjust_lr: True
use_exist_model: False
save_tensorlog: True
iseval: True
add_positive: False
savemodel: True

